version: '3'
services:
  server:
    build: .
    container_name: cms_webserver
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app/api
      - ./node_modules:/app/node_modules
      - ./docker/mongod.conf:/app/docker/mongod.conf
    links:
      - mongo
  mongo:
    container_name: cms_mongo
    image: mongo
    env_file: './.env'
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=cmsapi
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  adminmongo:
    image: mrvautin/adminmongo
    ports:
      - "1234:1234"
